In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv("labels_full_train_v1.csv")

In [49]:
df

,0,1,2,3,4,5,6,7,8,9,paths
0,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1800.tif
1,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1900.tif
2,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2000.tif
3,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2100.tif
4,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_500.tif
...,...,...,...,...,...,...,...,...,...,...,...
27265,0,0,0,0,0,0,0,0,0,1,chips/cloudfree-merge-polygons/split/train/92/92_900_4600.tif
27266,0,0,0,0,0,0,0,0,0,1,chips/cloudfree-merge-polygons/split/train/92/92_900_4700.tif
27267,0,0,0,0,0,0,0,0,0,1,chips/cloudfree-merge-polygons/split/train/92/92_900_4800.tif
27268,0,0,0,0,0,0,0,0,0,1,chips/cloudfree-merge-polygons/split/train/92/92_900_4900.tif
27269,0,0,0,0,0,0,0,0,0,1,chips/cloudfree-merge-polygons/split/train/92/92_900_5000.tif

In [50]:
only_ISL = df[df["1"] == 1]

In [51]:
ISL_dupes = pd.DataFrame(np.repeat(only_ISL.values,5,axis=0),columns=df.columns)

In [52]:
ISL_dupes

,0,1,2,3,4,5,6,7,8,9,paths
0,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1000.tif
1,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1000.tif
2,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1000.tif
3,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1000.tif
4,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1000.tif
...,...,...,...,...,...,...,...,...,...,...,...
18870,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
18871,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
18872,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
18873,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
18874,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif

In [53]:
ISL_oversampled = df.append(ISL_dupes).reset_index()

In [56]:
ISL_oversampled = ISL_oversampled.drop("index",axis=1)

In [57]:
pd.set_option('display.max_colwidth', -1)

/Users/purgatorid/opt/anaconda3/envs/ml-conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.

In [58]:
ISL_oversampled.loc[0]["paths"]

'chips/cloudfree-merge-polygons/split/train/1/1_1200_1800.tif'

In [59]:
"/".join(ISL_oversampled.loc[0,"paths"].split("/")[-3:])

'train/1/1_1200_1800.tif'

In [60]:
ISL_oversampled

,0,1,2,3,4,5,6,7,8,9,paths
0,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1800.tif
1,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1900.tif
2,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2000.tif
3,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2100.tif
4,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_500.tif
...,...,...,...,...,...,...,...,...,...,...,...
46140,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46141,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46142,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46143,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46144,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif

In [61]:
ISL_oversampled[ISL_oversampled["1"] == 1]

,0,1,2,3,4,5,6,7,8,9,paths
9,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1000.tif
15,0,1,0,0,0,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1600.tif
16,0,1,0,0,0,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1700.tif
17,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1300_1800.tif
24,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1400_1000.tif
...,...,...,...,...,...,...,...,...,...,...,...
46140,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46141,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46142,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46143,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46144,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif

In [62]:
ISL_oversampled[ISL_oversampled["4"] == 1]

,0,1,2,3,4,5,6,7,8,9,paths
0,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1800.tif
1,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1900.tif
2,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2000.tif
3,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2100.tif
4,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_500.tif
...,...,...,...,...,...,...,...,...,...,...,...
46130,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/91/91_900_1300.tif
46131,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/91/91_900_1300.tif
46132,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/91/91_900_1300.tif
46133,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/91/91_900_1300.tif
46134,0,1,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/91/91_900_1300.tif

In [63]:
ISL_oversampled["paths"]

0        chips/cloudfree-merge-polygons/split/train/1/1_1200_1800.tif
1        chips/cloudfree-merge-polygons/split/train/1/1_1200_1900.tif
2        chips/cloudfree-merge-polygons/split/train/1/1_1200_2000.tif
3        chips/cloudfree-merge-polygons/split/train/1/1_1200_2100.tif
4        chips/cloudfree-merge-polygons/split/train/1/1_1200_500.tif
                                    ...
46140    chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46141    chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46142    chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46143    chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46144    chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
Name: paths, Length: 46145, dtype: object

In [64]:
def remove_string(x):
    x =  "/".join(x.split("/")[-3:])
    return x

In [65]:
df2 = ISL_oversampled.copy()

In [66]:
df2

,0,1,2,3,4,5,6,7,8,9,paths
0,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1800.tif
1,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_1900.tif
2,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2000.tif
3,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_2100.tif
4,0,0,0,0,1,0,0,0,0,0,chips/cloudfree-merge-polygons/split/train/1/1_1200_500.tif
...,...,...,...,...,...,...,...,...,...,...,...
46140,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46141,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46142,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46143,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif
46144,0,1,0,0,0,0,0,0,1,0,chips/cloudfree-merge-polygons/split/train/91/91_900_900.tif

In [67]:
new_path = df2["paths"].apply(remove_string)

In [68]:
ISL_oversampled["paths"] = new_path

In [69]:
ISL_oversampled

       0  1  2  3  4  5  6  7  8  9                    paths
0      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_1800.tif
1      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_1900.tif
2      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_2000.tif
3      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_2100.tif
4      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_500.tif
...   .. .. .. .. .. .. .. .. .. ..                     ...
46140  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46141  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46142  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46143  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46144  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif

[46145 rows x 11 columns]

In [70]:
ISL_oversampled.to_csv("labels_full_train_v6.csv",index=False)

In [71]:
pd.read_csv("labels_full_train_v6.csv")

       0  1  2  3  4  5  6  7  8  9                    paths
0      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_1800.tif
1      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_1900.tif
2      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_2000.tif
3      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_2100.tif
4      0  0  0  0  1  0  0  0  0  0  train/1/1_1200_500.tif
...   .. .. .. .. .. .. .. .. .. ..                     ...
46140  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46141  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46142  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46143  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif
46144  0  1  0  0  0  0  0  0  1  0  train/91/91_900_900.tif

[46145 rows x 11 columns]

# Debug Unique Path ID Issue

In [ ]:
def get_label_from_csv(self, path_img):
    # testing if path in the training csv file or in the val one
    if path_img.numpy().decode() in self.labels_file_train.paths.to_list():
        ### Training csv
        # path_img is a tf.string and needs to be converted into a string using .numpy().decode()
        id = int(self.labels_file_train[self.labels_file_train.paths == path_img.numpy().decode()].index.values)
        # The list of labels (e.g [0,1,0,0,0,0,0,0,0,0] is grabbed from the csv file on the row where the s3 path is
        label = self.labels_file_train.drop('paths', 1).iloc[int(id)].to_list()
    else:
        ### Validation csv
        # path_img is a tf.string and needs to be converted into a string using .numpy().decode()
        id = int(self.labels_file_val[self.labels_file_val.paths == path_img.numpy().decode()].index.values)
        # The list of labels (e.g [0,1,0,0,0,0,0,0,0,0] is grabbed from the csv file on the row where the s3 path is
        label = self.labels_file_val.drop('paths', 1).iloc[int(id)].to_list()
    return label

In [74]:
csv_path = "/Users/purgatorid/Documents/GitHub/Project Canopy/cb_feature_detection/data-prep/labels_full_train_v6.csv"

In [83]:
df = pd.read_csv(csv_path)

In [ ]:
df[]

In [78]:
img_uri = df["paths"][0]

In [79]:
int(df[df["paths"] == img_uri].index.values)

0

In [82]:
df[df["paths"] == img_uri].index.values

array([0])